appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XuATN7YLpxBMoApqYriqHHLAO8tVezyCYEVrEqukRI1r8GC7OsZtZ4fBteS1UevyDHRMMW7sMh3Pt5uf6wuePG007X09+1pUhG5K8X+CDDU6hbYBC4BOA9SxjZnWvpngCSE9AW3btdeBkROrB9NYOhvuVB77t2SAKfEbrXtnIPpuWWXIdZ/o8tbORvSoKZ4m2yHTxZ/NcsX1SPFowzzyNGzlDq/3rrE9LYV0Fr0uEkZHj/LK6nXiZsEGN2UUexdNOJ3+Al+yKyWtAIOZn0TIEh8fwXA6eKMrGwgA94mauxlwtwGZ2Za/90xy6Hi3W/bHnAIAwBrG/ZIZv58p17NDCU8a2r2vsxzUrZeguKK3JElhrASdyXGmAuC3n6Ydl37qUvyg2GJkzGwJiZHBBUcv0CfHAqrwiQgzuISp2cdBdxGjA/XYAEVKaUbL9Z0X7bL3XzX5CT/2eSvtgiUY9GViQ4wynqfPKhUYiWF7Cpvzsj/Ngw5/8FB34kmTmRtXD4tEv9HKnTbtJBOM/oYrw5HBQryu5Xw6ZILT/1V16IS5XIzul0vwbxJwcsD9/UpYF5yoQufwggCUbK1wHuZAnDN4cntSUBIufLoqv0aHaIUfLol0zzvyDq9CO8XlGdt33z6+vqydcNq7K9/stEH3XBuBl0PWbT29aq/YL2RjY2Wu/6k=}
conda_forge_output_validation: true
